source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'TSMessages' do
    pod "TSMessages", :path => "../"
    
    target 'Tests' do
        inherit! :search_paths
        
        pod 'Specta', '~> 0.2.1'
        pod 'Expecta'
        pod 'FBSnapshotTestCase'
        pod 'Expecta+Snapshots'
    end
end
